server:
  port: 80

logging:
  level:
    org.springframework.security: DEBUG

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: users-service
          uri: http://user-service:8080 # here docker compose network or docker internal DNS resolves by service name
          predicates:
            - Path=/api/v1/users/**
        - id: products-service
          uri: http://product-service:8081
          predicates:
            - Path=/api/v1/products/**
app:
  jwt:
    secret: secureSecreteKeyShopNowProjectVisa2025! # MUST MATCH THE SECRET IN JwtUtil AND user-service
